name: Publish Extension

# 触发条件：当推送到主分支 或 创建新标签时触发工作流
# Trigger conditions: When pushing to main branch or creating new tag
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 升级到 Node.js 18 版本 / Upgrade to Node.js 18
          
      - name: Install dependencies
        run: npm install # 使用 npm install 替代 npm ci / Use npm install instead of npm ci
      
      - name: Lint & Test
        run: |
          npm run lint
          npm test
        
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Package Extension
        run: npm run package
        
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: "*.vsix"
          
      - name: Publish to Visual Studio Marketplace
        # 只有在创建标签时才发布到市场
        # Only publish to marketplace when creating a tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx vsce publish --force -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          
      - name: Create GitHub Release
        # 只有在创建标签时才创建 GitHub Release
        # Only create GitHub Release when creating a tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
