name: Publish Extension

# 触发条件：当推送到主分支 或 创建新标签时触发工作流
# Trigger conditions: When pushing to main branch or creating new tag
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Lint & Test
        run: |
          npm run lint
          npm test
        
      - name: Package Extension
        run: npm run package
        
      - name: Publish to Visual Studio Marketplace
        # 只有在创建标签时才发布到市场
        # Only publish to marketplace when creating a tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
